sudo: false
language: node_js
node_js: stable
env:
  global:
    secure: BpDB8Lxy8UkHInq96lqXtH8X7mGW93GgKgVgc6j/Kdjs1I82wGpJI32IhqnKhFf3z1F6Sdh1T/w6ZkYqNlbaETlBUPi52OmmWStRPf1AbpDGGsxcE5d7rxJwrsdhq56AMFkA68gYN4CRSux3JNyBlpux3Gfb0gvhn5sJoc97tMQ/lGkHHWHxqOiu7iAowz6pUXwO3F2DpQAyodumsdjhv9ApU/61s9fDNEd/05l6UyGTuVa9Kb08BozAXHcBTM0gmUrB6nhYXvoOQ7J+i8x+J1Lu14jw8sAWkNol1Uqs1W8MOp8omu3rTntXoItrVuDHhNo3z/RswGcmcaF1ixwyXYNXXWTTYFUuzkj83LU3SEZ4lUa6+W9l0TfmK4voi0w/VPlgAY57/86EMeEfgD8A73SUeEfcEPGj65O7exgBvwVmuU4/1RjccmC4/TLsnSYQv90MVlFp1Nb54c7GaKHEF2t5wWqqXObFSedDpsh+lb/iuaxL7jJu8dTZ4j+c1x3QNWNekc8JHoE9L0ZcwhnKbgZq/ynYhGyy7h31kGKgbPtQvZ8Y/MTRqjqvT1kfg9oWiNg2RKP3pYwGr3bGvrsS2g8pXqjn5BkjQuf3Lf6vk6zmWqRk28vCkDQwtoynwg3nzXWyDEyr76IYVpJe/MrtpPgZo70P4GArg8Tj/jZPF9E=
script:
  - npm run build
after_success:
# http://blog.eiel.info/blog/2014/02/18/github-push-from-travis/
#  https://github.com/creativelive/travis-key
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\nIdentityFile ~/.ssh/deploy.key\n" >> ~/.ssh/config
  - openssl aes-256-cbc -k "$SERVER_KEY" -in .travis/deploy_key.enc -d -a -out deploy.key
  - cp deploy.key ~/.ssh/
  - chmod 600 ~/.ssh/deploy.key
  - git config --global user.email "azuciao@gmail.com"
  - git config --global user.name "Travis"
  - npm run deploy
branches:
  except:
    - master